### ISSUE TITLE
bug: connecting but never connects

### ISSUE THREAD

**Issue by CamoeLMAO** [Martichou/rquickshare#83]
sending from one phone to pc used to be pretty smooth when using rqs 0.4.1. but now on the latest version it detects the pc, and it tries to connect, but it doesnt manage. the pc doesnt see my phone, no notification for file requests. it just fails. i dont know what's happening but i hope it gets fixed in a future update. im connected to the same wifi network. bluetooth works on both devices, but im dumbfounded.. (im on linux mint 21.4)
![Screenshot_20240511_203814_Quick Share](https://github.com/Martichou/rquickshare/assets/98377615/67291446-bbbb-4c31-9b3c-0fec420d9ac7)

**Comment by CamoeLMAO** [comment]
i just found out smth. when im sending from phone to pc, and the pc is hidden. it shows a notification that my phone is trying to send to my pc. but when i become temporarily visible. nothing happens.

**Comment by CamoeLMAO** [comment]
update 2: sending pc to phone works???? my phone shows up after a while on the sending screen. im so confused

**Comment by Martichou** [comment]
Hey! Sorry you're hitting an issue.

Just to be clear, does: sending from your phone to your computer works when the computer is in "Always visible" mode? (you may want to kill the app and restart it just to be sure)

If it works, then I'm not sure I got what the issue is. If it's not working, can you retry with 0.4.1 and tell me if it works on 0.4.1? 

As far as I remember, nothing have changed fundamentaly since 0.4.1 regarding connection/handling of requests :)

**Comment by Martichou** [comment]
Closing, reopen if needed.

**Comment by majal** [comment]
Hey, came over here for exactly the same problem. Using 0.7.1 AppImage on Ubuntu 24.04. Laptop is "Always visible". Phone to laptop just says connecting until it fails.

**Comment by Martichou** [comment]
@majal Can you execute r-quick-share using the terminal to gather the log?

```
env RQS_LOG=trace r-quick-share
```

**Comment by honnip** [comment]
On 0.7.1 release, it seems that it's missing the debug, trace logs.
 
```shell
~~> RQS_LOG=trace rquickshare 
2024-06-11T06:03:52Z  INFO rqs_lib: TcpListener on: 0.0.0.0:34049
2024-06-11T06:03:52Z  INFO rqs_lib::manager: TcpServer: service starting
2024-06-11T06:03:52Z  INFO rqs_lib::hdl::mdns: Broadcasting with: acrux
2024-06-11T06:03:52Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting

** (r-quick-share:93404): WARNING **: 15:04:18.000: atk-bridge: get_device_events_reply: unknown signature
```

**Comment by Martichou** [comment]
Sorry for the late reply, seems like the env variable is only taken into account for a debug build. I'm adding a way to change the logging level using the config file. I'll make a release soon and we then should be able to gather log :)

**Comment by Martichou** [comment]
See: https://github.com/Martichou/rquickshare/pull/104#issuecomment-2179485060

**Comment by MarSoft** [comment]
Just had this same issue: rquickshare 0.7.1 on NixOS, fresh installed rquickshare and trying to send file from my phone. Laptop could be seen from the phone, but sending a file resulted in long "Connecting..." time and then failure — nothing happening on the laptop.
After some struggle I've tried to send a file the other way round (from laptop to the phone) while the phone was still trying to send a file. And voilá — I got a file receiving confirmation on the laptop.
Now I cannot reproduce the issue. For me it looks like some system-wide (?) state was changed, maybe some service started(?). Removing `~/.local/share/dev.mandre.rquickshare/.settings.json` does not return the issue. Did not try to reboot the system though.

**Comment by Martichou** [comment]
I may have an idea, I once noticed a deadlock in a WIP state (not master) for when the core_lib was sending a message in the broadcast channel but got stuck sending maybe due to the receiver not being able to receive it. Seems strange but I'll take a look at that possibility until someone grab a log :)

**Comment by Martichou** [comment]
Update: I do think https://github.com/Martichou/rquickshare/commit/8b9d1824bfa7b70bef124218a56d024b9105903e should fix this. 

I'll tag the v0.8.2 and close this issue. But if someone is able to reproduce with the soon to be v0.8.2, reopen and I'll check :)

**Comment by honnip** [comment]
Thank you for the fixes. 

I can still reproduce this with 0.8.2
```shell
~~> RQS_LOG=trace rquickshare
set_up_logging: level asked: "trace"
set_up_logging: level: Trace
2024-06-23T01:41:47Z DEBUG rquickshare::logger: Finished setting up logging! yay!
2024-06-23T01:41:47Z DEBUG rquickshare: Starting setup of RQuickShare app
2024-06-23T01:41:47Z TRACE rquickshare: Beginning of RQS start
2024-06-23T01:41:47Z  INFO rqs_lib: TcpListener on: 0.0.0.0:45101
2024-06-23T01:41:47Z  INFO rqs_lib::manager: TcpServer: service starting
2024-06-23T01:41:47Z  INFO rqs_lib::hdl::mdns: Broadcasting with: acrux
2024-06-23T01:41:47Z  INFO rqs_lib::hdl::ble: BleListener: service starting
2024-06-23T01:41:47Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting
2024-06-23T01:41:47Z DEBUG rqs_lib::hdl::mdns: MDnsServer: visibility changed: Visible
2024-06-23T01:42:08Z DEBUG rqs_lib::hdl::ble: BleListener: A device (hci0/dev_71_61_A9_77_17_8E) is sharing ({0000fe2c-0000-1000-8000-00805f9b34fb: [252, 18, 142, 5, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 112, 189, 167, 38, 146, 136, 155, 37, 0]}) nearby
2024-06-23T01:42:08Z DEBUG rqs_lib::hdl::mdns: MDnsServer: ble_receiver: got event
2024-06-23T01:42:08Z TRACE rquickshare: Tauri: ble received: Visible

** (r-quick-share:13655): WARNING **: 10:42:12.833: atk-bridge: get_device_events_reply: unknown signature
2024-06-23T01:42:39Z DEBUG rqs_lib::hdl::ble: BleListener: A device (hci0/dev_71_61_A9_77_17_8E) is sharing ({0000fe2c-0000-1000-8000-00805f9b34fb: [252, 18, 142, 5, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 112, 189, 167, 38, 146, 136, 155, 37, 0]}) nearby
2024-06-23T01:42:39Z DEBUG rqs_lib::hdl::mdns: MDnsServer: ble_receiver: got event
2024-06-23T01:42:39Z TRACE rquickshare: Tauri: ble received: Visible
2024-06-23T01:43:10Z DEBUG rqs_lib::hdl::ble: BleListener: A device (hci0/dev_71_61_A9_77_17_8E) is sharing ({0000fe2c-0000-1000-8000-00805f9b34fb: [252, 18, 142, 5, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 112, 189, 167, 38, 146, 136, 155, 37, 0]}) nearby
2024-06-23T01:43:10Z DEBUG rqs_lib::hdl::mdns: MDnsServer: ble_receiver: got event
2024-06-23T01:43:10Z TRACE rquickshare: Tauri: ble received: Visible
2024-06-23T01:43:41Z DEBUG rqs_lib::hdl::ble: BleListener: A device (hci0/dev_71_61_A9_77_17_8E) is sharing ({0000fe2c-0000-1000-8000-00805f9b34fb: [252, 18, 142, 5, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 184, 112, 189, 167, 38, 146, 136, 155, 37, 0]}) nearby
2024-06-23T01:43:41Z DEBUG rqs_lib::hdl::mdns: MDnsServer: ble_receiver: got event
2024-06-23T01:43:41Z TRACE rquickshare: Tauri: ble received: Visible
2024-06-23T01:44:14Z DEBUG rqs_lib::hdl::ble: BleListener: A device (hci0/dev_4E_D3_66_0C_3B_16) is sharing ({0000fe2c-0000-1000-8000-00805f9b34fb: [252, 18, 142, 5, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 54, 182, 13, 154, 166, 49, 107, 89, 0]}) nearby
2024-06-23T01:44:14Z DEBUG rqs_lib::hdl::mdns: MDnsServer: ble_receiver: got event
2024-06-23T01:44:14Z TRACE rquickshare: Tauri: ble received: Visible
```

**Comment by honnip** [comment]
Ah it was firewall. It works well after I opened the ports.

**Comment by evening-hs** [comment]
@honnip which ports did you open?

**Comment by evening-hs** [comment]
Followup, this is how you find the port to open, (apparently it may change?)

```
rquickshare:29023): libayatana-appindicator-WARNING **: 20:19:55.534: libayatana-appindicator is deprecated. Please use libayatana-appindicator-glib in newly written code.
2026-02-17T02:19:55Z  INFO rqs_lib: TcpListener on: 0.0.0.0:35715 <==== this is the port
2026-02-17T02:19:55Z  INFO rqs_lib::manager: TcpServer: service starting
2026-02-17T02:19:55Z  INFO rqs_lib::hdl::mdns: Broadcasting with: cachyos
2026-02-17T02:19:55Z  INFO rqs_lib::hdl::ble: BleListener: service starting
2026-02-17T02:19:55Z  INFO rqs_lib::hdl::mdns: MDnsServer: service starting
```
